name: CI Pipeline

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test

3.	Push your workflow file:
bash
CopyEdit
git checkout -b feature/ci-setup
git add .
git commit -m "Add GitHub Actions CI workflow"
git push -u origin feature/ci-setup
